name: Docker CI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  REPOSITORY_ZEROTIER: jerryin/zerotier
  REPOSITORY_ZEROTIER_MOON: jerryin/zerotier-moon

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ZeroTier Docker meta
        id: zerotier_meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REPOSITORY_ZEROTIER }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: ZeroTier Moon Docker meta
        id: zerotier_moon_meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REPOSITORY_ZEROTIER_MOON }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ZeroTier Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./zerotier/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.zerotier_meta.outputs.tags }}
          labels: ${{ steps.zerotier_meta.outputs.labels }}

      - name: ZeroTier Moon Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./zerotier-moon/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.zerotier_moon_meta.outputs.tags }}
          labels: ${{ steps.zerotier_moon_meta.outputs.labels }}
